import Footer from "./components/Footer";
import Header from "./components/Header";
import { ErrorWrapper } from "./error-wrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ErrorWrapper>{children}</ErrorWrapper>
        <Footer />
      </body>
    </html>
  );
}
